#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Nanzhu_Seq_V2

#include "Basic.hpp"

#include "BP_BaseRole_Seq_V2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Nanzhu_Seq_V2.BP_Nanzhu_Seq_V2_C
// 0x0000 (0x0388 - 0x0388)
class ABP_Nanzhu_Seq_V2_C final : public ABP_BaseRole_Seq_V2_C
{
public:
	void UserConstructionScript();
	void SwitchMeshTransform(bool LevelA);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Nanzhu_Seq_V2_C">();
	}
	static class ABP_Nanzhu_Seq_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Nanzhu_Seq_V2_C>();
	}
};
static_assert(alignof(ABP_Nanzhu_Seq_V2_C) == 0x000008, "Wrong alignment on ABP_Nanzhu_Seq_V2_C");
static_assert(sizeof(ABP_Nanzhu_Seq_V2_C) == 0x000388, "Wrong size on ABP_Nanzhu_Seq_V2_C");

}

