#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhotographCameraConfig

#include "Basic.hpp"

#include "EPhotographCamera_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PhotographCameraConfig.BP_PhotographCameraConfig_C
// 0x0050 (0x0088 - 0x0038)
class UBP_PhotographCameraConfig_C final : public UPrimaryDataAsset
{
public:
	TMap<EPhotographCamera, float>                基础;                                              // 0x0038(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PhotographCameraConfig_C">();
	}
	static class UBP_PhotographCameraConfig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PhotographCameraConfig_C>();
	}
};
static_assert(alignof(UBP_PhotographCameraConfig_C) == 0x000008, "Wrong alignment on UBP_PhotographCameraConfig_C");
static_assert(sizeof(UBP_PhotographCameraConfig_C) == 0x000088, "Wrong size on UBP_PhotographCameraConfig_C");
static_assert(offsetof(UBP_PhotographCameraConfig_C, 基础) == 0x000038, "Member 'UBP_PhotographCameraConfig_C::基础' has a wrong offset!");

}

