#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_DayNightEvent

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_DayNightEvent.BPI_DayNightEvent_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_DayNightEvent_C final
{
public:
	void OnEnterDay();
	void OnEnterNight();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_DayNightEvent_C">();
	}
	static class IBPI_DayNightEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_DayNightEvent_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_DayNightEvent_C) == 0x000001, "Wrong alignment on IBPI_DayNightEvent_C");
static_assert(sizeof(IBPI_DayNightEvent_C) == 0x000001, "Wrong size on IBPI_DayNightEvent_C");

}

