#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_AnimalEcological

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_AnimalEcological.BPI_AnimalEcological_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_AnimalEcological_C final
{
public:
	void SystemUiEnd();
	void SystemUiStart();
	void FeedStart(const struct FGameplayTag& GameplayTag);
	void GetCurrentActionTime(float* ActionTime);
	void NoneStateEnd();
	void NoneStateStart();
	void StateMachineInitializationComplete();
	void InteractEnd();
	void InteractStart();
	void IdleEnd();
	void IdleStart();
	void UnderAttackEnd();
	void UnderAttackStart();
	void AlertEnd();
	void AlertStart();
	void TakeOffEnd();
	void TakeOffStart();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_AnimalEcological_C">();
	}
	static class IBPI_AnimalEcological_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_AnimalEcological_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_AnimalEcological_C) == 0x000001, "Wrong alignment on IBPI_AnimalEcological_C");
static_assert(sizeof(IBPI_AnimalEcological_C) == 0x000001, "Wrong size on IBPI_AnimalEcological_C");

}

