#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SGameplayTagArray

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"


namespace SDK
{

// UserDefinedStruct SGameplayTagArray.SGameplayTagArray
// 0x0010 (0x0010 - 0x0000)
struct FSGameplayTagArray final
{
public:
	TArray<struct FGameplayTag>                   Value_4_9B2A497A42D6C94CD75B1680C8058A51;          // 0x0000(0x0010)(Edit, BlueprintVisible)
};
static_assert(alignof(FSGameplayTagArray) == 0x000008, "Wrong alignment on FSGameplayTagArray");
static_assert(sizeof(FSGameplayTagArray) == 0x000010, "Wrong size on FSGameplayTagArray");
static_assert(offsetof(FSGameplayTagArray, Value_4_9B2A497A42D6C94CD75B1680C8058A51) == 0x000000, "Member 'FSGameplayTagArray::Value_4_9B2A497A42D6C94CD75B1680C8058A51' has a wrong offset!");

}

