#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyStateShowUiCalabashEffect

#include "Basic.hpp"

#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsAnimNotifyStateShowUiCalabashEffect.TsAnimNotifyStateShowUiCalabashEffect_C
// 0x0010 (0x0098 - 0x0088)
class UTsAnimNotifyStateShowUiCalabashEffect_C final : public UKuroEffectMakerANS
{
public:
	class FName                                   EffectSlotName;                                    // 0x0088(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PlayOnEnd;                                         // 0x0094(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	bool K2_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration);
	bool K2_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);
	bool K2_NotifyTick(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float FrameDeltaTime);
	void Init();

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TsAnimNotifyStateShowUiCalabashEffect_C">();
	}
	static class UTsAnimNotifyStateShowUiCalabashEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyStateShowUiCalabashEffect_C>();
	}
};
static_assert(alignof(UTsAnimNotifyStateShowUiCalabashEffect_C) == 0x000008, "Wrong alignment on UTsAnimNotifyStateShowUiCalabashEffect_C");
static_assert(sizeof(UTsAnimNotifyStateShowUiCalabashEffect_C) == 0x000098, "Wrong size on UTsAnimNotifyStateShowUiCalabashEffect_C");
static_assert(offsetof(UTsAnimNotifyStateShowUiCalabashEffect_C, EffectSlotName) == 0x000088, "Member 'UTsAnimNotifyStateShowUiCalabashEffect_C::EffectSlotName' has a wrong offset!");
static_assert(offsetof(UTsAnimNotifyStateShowUiCalabashEffect_C, PlayOnEnd) == 0x000094, "Member 'UTsAnimNotifyStateShowUiCalabashEffect_C::PlayOnEnd' has a wrong offset!");

}

