#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsSkeletalObserver

#include "Basic.hpp"

#include "TsSkeletalObserver_classes.hpp"
#include "TsSkeletalObserver_parameters.hpp"


namespace SDK
{

// Function TsSkeletalObserver.TsSkeletalObserver_C.ReceiveTick
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATsSkeletalObserver_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsSkeletalObserver_C", "ReceiveTick");

	Params::TsSkeletalObserver_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TsSkeletalObserver.TsSkeletalObserver_C.ExecuteUbergraph_TsSkeletalObserver
// (Final, UbergraphFunction, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATsSkeletalObserver_C::ExecuteUbergraph_TsSkeletalObserver(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsSkeletalObserver_C", "ExecuteUbergraph_TsSkeletalObserver");

	Params::TsSkeletalObserver_C_ExecuteUbergraph_TsSkeletalObserver Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

