#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsUiHomeHelper

#include "Basic.hpp"

#include "LGUI_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsUiHomeHelper.TsUiHomeHelper_C
// 0x0000 (0x0100 - 0x0100)
class UTsUiHomeHelper_C final : public ULGUIBehaviour
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TsUiHomeHelper_C">();
	}
	static class UTsUiHomeHelper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsUiHomeHelper_C>();
	}
};
static_assert(alignof(UTsUiHomeHelper_C) == 0x000008, "Wrong alignment on UTsUiHomeHelper_C");
static_assert(sizeof(UTsUiHomeHelper_C) == 0x000100, "Wrong size on UTsUiHomeHelper_C");

}

