#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Nvzhu_Gameplay_Default

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Nvzhu_Gameplay_Default.ABP_Nvzhu_Gameplay_Default_C
// 0x0040 (0x0810 - 0x07D0)
class UABP_Nvzhu_Gameplay_Default_C final : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x07D8(0x0038)()

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void ExecuteUbergraph_ABP_Nvzhu_Gameplay_Default(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Nvzhu_Gameplay_Default_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Nvzhu_Gameplay_Default_C")
	}
	static class UABP_Nvzhu_Gameplay_Default_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Nvzhu_Gameplay_Default_C>();
	}
};
DUMPER7_ASSERTS_UABP_Nvzhu_Gameplay_Default_C;

}

