#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Renderer

#include "Basic.hpp"

#include "Renderer_classes.hpp"
#include "Renderer_parameters.hpp"


namespace SDK
{

// Function Renderer.KuroCaptureEventManager.Get
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UKuroCaptureEventManager*         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UKuroCaptureEventManager* UKuroCaptureEventManager::Get()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroCaptureEventManager", "Get");

	Params::KuroCaptureEventManager_Get Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

