#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Renderer

#include "Basic.hpp"


namespace SDK::Params
{

// Function Renderer.KuroCaptureEventManager.Get
// 0x0008 (0x0008 - 0x0000)
struct KuroCaptureEventManager_Get final
{
public:
	class UKuroCaptureEventManager*               ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroCaptureEventManager_Get;

}

